version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DOCKER=sim
      - FLASK_ENV=development
      - TEMPLATES_AUTO_RELOAD=True
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000 --reload
